name: Build
on: 
  push: 
    branches: ['main']

env: 
  NODE_VERSION: 18

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies and build
        run: npm ic & npm run build